"""
GABRIEL Structure Initializer
═════════════════════════════════════════════════════════════════════

Initializes the GABRIEL folder structure and configuration files.

"""

from __future__ import annotations

from datetime import datetime
from pathlib import Path
from typing import List

from gabriel.config import VERSION, FULL_NAME, Folders
from gabriel.console import console
from gabriel.utils import PathManager, safe_mkdir


class Initializer:
    """
    Initializes the GABRIEL folder structure.
    
    Creates all managed directories and initial configuration files.
    """
    
    def __init__(self, paths: PathManager) -> None:
        self.paths = paths
    
    # ─────────────────────────────────────────────────────────────────
    # Initialization
    # ─────────────────────────────────────────────────────────────────
    
    def initialize(self, force: bool = False) -> bool:
        """
        Create the canonical folder structure.
        
        Args:
            force: Recreate even if exists
            
        Returns:
            True if initialized, False if already exists
        """
        console.section("Initializing GABRIEL Structure")
        
        # Check if already initialized
        if self.is_initialized() and not force:
            console.warning("Structure already initialized")
            console.info("Use --force to reinitialize")
            return False
        
        # Create directories
        created = self._create_directories()
        
        # Create README
        self._create_readme()
        
        # Create .gitkeep files
        self._create_gitkeeps()
        
        # Create policies/config
        self._create_default_config()
        
        console.success(f"Created {created} directories")
        console.success("Structure initialized!")
        
        return True
    
    def is_initialized(self) -> bool:
        """Check if structure is already initialized."""
        return self.paths.control_plane.exists()
    
    # ─────────────────────────────────────────────────────────────────
    # Directory Creation
    # ─────────────────────────────────────────────────────────────────
    
    def _create_directories(self) -> int:
        """Create all managed directories."""
        created = 0
        
        for path in self.paths.all_managed_dirs():
            if not path.exists():
                safe_mkdir(path)
                console.debug(f"Created: {path.relative_to(self.paths.root)}")
                created += 1
        
        return created
    
    # ─────────────────────────────────────────────────────────────────
    # File Creation
    # ─────────────────────────────────────────────────────────────────
    
    def _create_readme(self) -> None:
        """Create control plane README."""
        readme_path = self.paths.control_plane / "README.md"
        
        if readme_path.exists():
            return
        
        content = f"""# {FULL_NAME} Control Plane

> Auto-generated by GABRIEL v{VERSION}

## 📁 Structure

```
{Folders.CONTROL_PLANE}/      # This directory - manifests, logs, policies
{Folders.INTAKE}/             # Incoming files staging area
{Folders.DEDUP}/              # Duplicate detection workspace
{Folders.PROJECTS}/           # Organized project repositories
{Folders.LIBRARIES}/          # Shared libraries and loose code
{Folders.AUTOMATIONS}/        # Scripts and automation tools
{Folders.TEMPLATES}/          # Project templates
{Folders.ARCHIVE}/            # Archived/deprecated items
```

## 🚀 Quick Start

```bash
# Initialize structure
gabriel init

# Plan organization (dry-run)
gabriel plan

# Review the plan
cat {Folders.CONTROL_PLANE}/manifest/move_plan.json

# Apply the plan
gabriel apply

# Check status
gabriel status
```

## 📋 Commands

| Command | Description |
|---------|-------------|
| `gabriel init` | Initialize folder structure |
| `gabriel plan` | Create organization plan (dry-run) |
| `gabriel apply` | Execute the plan |
| `gabriel apply --dry-run` | Preview changes without applying |
| `gabriel status` | Show current organization status |
| `gabriel scan` | Generate file fingerprints |
| `gabriel dedupe` | Find duplicate files |
| `gabriel validate` | Check structure integrity |
| `gabriel rollback` | Undo last apply operation |
| `gabriel rewrite_refs` | Update import paths after moves |
| `gabriel verify_refs` | Verify no old references remain |
| `gabriel nuke` | Remove original sources (ARM=NUKE required) |

## 📂 Manifest Files

| File | Purpose |
|------|---------|
| `manifest/move_plan.json` | Current move plan |
| `manifest/fingerprints.json` | File hashes for deduplication |
| `manifest/duplicates.json` | Duplicate file report |

## 📜 Logs

All operations are logged in `logs/` with timestamps.

## 🔄 Rollback

The `rollback/` directory contains information to undo operations.
Use `gabriel rollback` to restore previous state.

---
Generated: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}
"""
        
        readme_path.write_text(content, encoding="utf-8")
        console.debug("Created README.md")
    
    def _create_gitkeeps(self) -> None:
        """Create .gitkeep files in empty directories."""
        for path in self.paths.all_managed_dirs():
            if path.exists():
                # Only add .gitkeep if directory is empty
                contents = list(path.iterdir())
                if not contents:
                    gitkeep = path / ".gitkeep"
                    gitkeep.touch()
    
    def _create_default_config(self) -> None:
        """Create default configuration files."""
        # Create policies directory with default policy
        policy_path = self.paths.policies_dir / "default.yaml"
        
        if policy_path.exists():
            return
        
        content = """# GABRIEL Default Policy
# ════════════════════════════════════════════════════════════════════

version: "1.0"

# Ignored directories (never organized)
ignore_dirs:
  - node_modules
  - __pycache__
  - .venv
  - venv
  - .git
  - .idea
  - .vscode
  - dist
  - build
  - target

# Ignored files
ignore_files:
  - .DS_Store
  - Thumbs.db
  - "*.pyc"
  - "*.pyo"

# File size limits
limits:
  max_file_size_mb: 100
  max_files_per_scan: 100000

# Language priorities for detection
language_priority:
  - rust
  - go
  - python
  - typescript
  - javascript

# Safety settings
safety:
  require_arm_for_nuke: true
  confirm_large_moves: true
  backup_before_apply: false
"""
        
        safe_mkdir(policy_path.parent)
        policy_path.write_text(content, encoding="utf-8")
        console.debug("Created default policy")
    
    # ─────────────────────────────────────────────────────────────────
    # Status
    # ─────────────────────────────────────────────────────────────────
    
    def get_structure_status(self) -> dict:
        """Get status of the structure."""
        status = {
            "initialized": self.is_initialized(),
            "directories": {},
        }
        
        for path in self.paths.all_managed_dirs():
            rel_path = str(path.relative_to(self.paths.root))
            status["directories"][rel_path] = {
                "exists": path.exists(),
                "files": len(list(path.iterdir())) if path.exists() else 0,
            }
        
        return status
